[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://your-supabase-url.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-supabase-anon-key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 