[build]
  base = "aarhus-biludlejning"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "din_supabase_url"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "din_supabase_anon_key" 